#!/bin/bash
# Installs the Translate app: clones/updates ~/.translate-app, sets up
# backend deps, downloads the minimum ASR weights needed for first launch
# (Gipformer + tiny.en Whisper — everything else downloads lazily on first
# selection, see backend/scripts/download_models.sh), builds the Swift app
# via a real Xcode project (generated by xcodegen from macapp/project.yml —
# see PLAN.md step 0 for why this replaced an earlier hand-assembled-bundle
# approach), and installs it to /Applications.
#
# Safe to re-run: acts as an update mechanism (git pull, re-sync deps,
# rebuild, re-copy over /Applications/Translate.app).
set -euo pipefail

REPO_URL="https://github.com/hienhayho/realtime-translator.git"
INSTALL_DIR="$HOME/.translate-app"
APP_NAME="Translate.app"

log() { printf '\n=== %s ===\n' "$1"; }
fail() { printf 'error: %s\n' "$1" >&2; exit 1; }

# --- 1. Preflight ------------------------------------------------------
log "Preflight checks"

command -v brew >/dev/null 2>&1 || fail "Homebrew not found. Install it first: https://brew.sh"
command -v git >/dev/null 2>&1 || fail "git not found (should ship with Xcode Command Line Tools)."
xcode-select -p >/dev/null 2>&1 || fail "Xcode Command Line Tools not found. Run: xcode-select --install"
command -v swift >/dev/null 2>&1 || fail "swift not found — install Xcode / Command Line Tools."

if [ "$(uname -m)" != "arm64" ]; then
    fail "This app is built for Apple Silicon (arm64) only — detected $(uname -m)."
fi

echo "OK"

# Optional: huggingface_hub reads HF_TOKEN from the environment automatically
# and uses it for higher rate limits / faster downloads (used later in step 5).
# Not required — without one, downloads still work, just slower and
# rate-limited (the "unauthenticated requests" warning huggingface_hub
# prints is expected and harmless). Skip the prompt entirely if HF_TOKEN is
# already set, or if stdin isn't a terminal (e.g. running non-interactively/
# piped/CI). Asked up front so the rest of the install can run unattended.
if [ -z "${HF_TOKEN:-}" ] && [ -t 0 ]; then
    read -r -p "Hugging Face token (optional, speeds up downloads — press Enter to skip): " HF_TOKEN_INPUT
    if [ -n "$HF_TOKEN_INPUT" ]; then
        export HF_TOKEN="$HF_TOKEN_INPUT"
    fi
fi

# --- 2. Clone / update ---------------------------------------------------
log "Cloning/updating $INSTALL_DIR"

if [ -d "$INSTALL_DIR/.git" ]; then
    echo "Existing install found — pulling latest."
    git -C "$INSTALL_DIR" pull --ff-only || fail "git pull failed — resolve local changes in $INSTALL_DIR manually and re-run."
else
    git clone "$REPO_URL" "$INSTALL_DIR"
fi

# --- 3. Backend deps ------------------------------------------------------
log "Backend dependencies (uv sync)"

UV_BIN=""
for candidate in "$HOME/.local/bin/uv" "/opt/homebrew/bin/uv" "/usr/local/bin/uv"; do
    if [ -x "$candidate" ]; then
        UV_BIN="$candidate"
        break
    fi
done
if [ -z "$UV_BIN" ] && command -v uv >/dev/null 2>&1; then
    UV_BIN="$(command -v uv)"
fi
[ -n "$UV_BIN" ] || fail "uv not found. Install it: https://docs.astral.sh/uv/"

(cd "$INSTALL_DIR/backend" && "$UV_BIN" sync)

# --- 4. llama-server -------------------------------------------------------
log "llama.cpp (llama-server)"

if brew list llama.cpp >/dev/null 2>&1; then
    echo "Already installed."
else
    brew install llama.cpp
fi

# --- 5. Model weights (Gipformer + tiny.en only — everything else is lazy) -
log "Downloading minimum ASR weights (Gipformer + Whisper tiny.en)"

# download_models.sh shells out to `python` internally (via huggingface_hub),
# so it needs to run inside the uv-managed venv — use `uv run sh` rather than
# a bare `sh`, so the venv's python (with huggingface_hub installed) is on PATH.
(cd "$INSTALL_DIR/backend" && "$UV_BIN" run sh scripts/download_models.sh)

# --- 6. Build the Swift app -------------------------------------------------
log "Building Translate.app"

command -v xcodegen >/dev/null 2>&1 || {
    echo "xcodegen not found — installing via Homebrew."
    brew install xcodegen
}

(cd "$INSTALL_DIR/macapp" && xcodegen generate)

BUILD_DIR="$(mktemp -d)"
xcodebuild -project "$INSTALL_DIR/macapp/Translate.xcodeproj" \
    -scheme Translate \
    -configuration Release \
    -derivedDataPath "$BUILD_DIR" \
    build

BUILT_APP="$BUILD_DIR/Build/Products/Release/$APP_NAME"
[ -d "$BUILT_APP" ] || fail "Build succeeded but $APP_NAME not found at expected path."

# --- 7. Install --------------------------------------------------------
log "Installing to /Applications"

if [ -d "/Applications/$APP_NAME" ]; then
    rm -rf "/Applications/$APP_NAME"
fi
cp -R "$BUILT_APP" "/Applications/$APP_NAME"
rm -rf "$BUILD_DIR"

echo "Installed: /Applications/$APP_NAME"
echo ""
echo "Note: this build is ad-hoc signed (no paid Apple Developer ID)."
echo "macOS will re-prompt for microphone access after every reinstall/update"
echo "— this is expected, not a bug."

# --- 8. Launch -----------------------------------------------------------
log "Launching"
open "/Applications/$APP_NAME"
